name: cron scrapy crawl
run-name: crawl
on:
  schedule:
    - cron: '1 0 * * *'
  workflow_dispatch: {}
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: Check out security-scraper
        uses: actions/checkout@v3
      - name: Check out security-scraper-output
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SECURITY_SCRAPER_OUTPUT_DEPLOY_KEY }}
          repository: defenseunicorns/security-scraper-output
          path: output
      - name: install
        run: |
          pip3 install wheel
          pip3 install .
      - name: scrapy crawl atlassian_security_advisories
        continue-on-error: true
        run: |
          scrapy crawl atlassian_security_advisories -s OUTPUT_DIRECTORY=output
      - name: scrapy crawl feeds
        continue-on-error: true
        run: |
          scrapy crawl feeds -s OUTPUT_DIRECTORY=output
      - name: scrapy crawl github_security_advisories
        continue-on-error: true
        run: |
          scrapy crawl github_security_advisories -s OUTPUT_DIRECTORY=output
      - name: scrapy crawl mattermost_security_updates
        continue-on-error: true
        run: |
          scrapy crawl mattermost_security_updates -s OUTPUT_DIRECTORY=output
      - name: push
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          # A GitHub deploy key with push permissions is used to write to the security-scraper-output repo
          ssh-agent -a "$SSH_AUTH_SOCK" > /dev/null
          ssh-add - <<< "${{ secrets.SECURITY_SCRAPER_OUTPUT_DEPLOY_KEY }}"

          # TODO: consider using GitHub GraphQL API for committing to repo

          git config --global user.email "github-actions@example.invalid"
          git config --global user.name "GitHub Actions"

          cd output
          git_status=$(git status --porcelain)
          if [ -z "$git_status" ]; then
            exit
          fi
          git add .
          git commit -m "automated crawl"
          git push
